parameters:
#    guard_common_health.example.class: Guard\Common\HealthBundle\Example

services:
#    guard_common_health.example:
#        class: %guard_common_health.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
