guard_common_animal_homepage:
    pattern:  /animal
    defaults: { _controller: GuardCommonAnimalBundle:Default:index }
guard_common_animal_new:
    pattern: /animal/new/{id_type}
    defaults: { _controller: GuardCommonAnimalBundle:Default:new }
    requirements:
        id: \d+
guard_common_animal_selectype:
    pattern: /animal/selecttype
    defaults: { _controller: GuardCommonAnimalBundle:Default:newselecttype }
guard_common_animal_race:
    pattern:  /race
    defaults: { _controller: GuardCommonAnimalBundle:Race:index }
guard_common_animal_race_new:
    pattern: /race/new
    defaults: { _controller:GuardCommonAnimalBundle:Race:new }
guard_common_animal_race_delete:
    pattern: /race/delete/{id}
    defaults: { _controller:GuardCommonAnimalBundle:Race:delete }
    requirements:
        id: \d+
guard_common_animal_unlink:
    pattern: /animal/unlink/{id}
    defaults: { _controller:GuardCommonAnimalBundle:Default:unlink }
    requirements:
        id: \d+
guard_common_animal_link:
    pattern: /animal/link
    defaults: { _controller:GuardCommonAnimalBundle:Default:link }
#guard_common_animal_add:
#    pattern: /animal/new
#    defaults: {_controller: GuardCommonAnimalBundle:Default:new }
#guard_common_animal_del:
#    pattern: /animal/delete
#    defaults: {_controller: GuardCommonAnimalBundle:Default:delete }
#guard_common_animal_update:
#    pattern: /animal/update
#    defaults: {_controller: GuardCommonAnimalBundle:Default:update }
#guard_common_animal_detail:
#    pattern: /animal/{id}
#    defaults: { _controller: GuardCommonAnimalBundle:Default:detail }
#    requirements:
#        id: \d+
