guard_common_health:
    resource: "@GuardCommonHealthBundle/Resources/config/routing.yml"
    prefix:   /

guard_common_event:
    resource: "@GuardCommonEventBundle/Resources/config/routing.yml"
    prefix:   /

guard_common_balance:
    resource: "@GuardCommonBalanceBundle/Resources/config/routing.yml"
    prefix:   /

guard_common_gamelle:
    resource: "@GuardCommonGamelleBundle/Resources/config/routing.yml"
    prefix:   /

guard_common_animal:
    resource: "@GuardCommonAnimalBundle/Resources/config/routing.yml"
    prefix:   /

guard_apiv1:
    resource: "@GuardApiv1Bundle/Resources/config/routing.yml"
    prefix:   /

guard_common_user:
    resource: "@GuardCommonUserBundle/Resources/config/routing.yml"
    prefix:   /

guard_common_public:
    resource: "@GuardCommonPublicBundle/Resources/config/routing.yml"
    prefix:   /


fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
 
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile
 
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
 
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
 
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile