guard_common_gamelle_homepage:
    pattern:  /gamelle
    defaults: { _controller: GuardCommonGamelleBundle:Default:index }
guard_common_gamelle_new:
    pattern:  /gamelle/new
    defaults: { _controller: GuardCommonGamelleBundle:Default:new }
