parameters:
#    guard_common_gamelle.example.class: Guard\Common\GamelleBundle\Example

services:
#    guard_common_gamelle.example:
#        class: %guard_common_gamelle.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
